[package]
name = "global-hotkeys"
version = "0.0.1"
edition = "2021"

authors = ["Bay"]
repository = "https://github.com/zX3no/global-hotkeys"
readme = "README.md"
license = "MIT"

[dependencies]
winapi = { version = "0.3.8", features = ["winuser"] }